---
- name: Add apt-key for last mongodb repository 
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

- name: Add repository for last mongodb package
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.0 multiverse' state=present update_cache=yes

- name: install mongodb and other dependencies
  apt: name={{ item }} state=installed
  with_items:
   - "mongodb-org={{mongodb_org_version}}"
   - "mongodb-org-server={{mongodb_org_server_version}}" 
   - "mongodb-org-shell={{mongodb_org_shell_version}}"
   - "mongodb-org-mongos={{mongodb_org_mongos_version}}"
   - "mongodb-org-tools={{mongodb_org_tools_version}}"
   - python-pymongo

- name: Prevent upgrading on mongo packages 
  shell: echo "{{item}} hold" | sudo dpkg --set-selections
  with_items:
  - "mongodb-org"
  - "mongodb-org-server" 
  - "mongodb-org-shell" 
  - "mongodb-org-mongos"
  - "mongodb-org-tools" 



- name: Start the mongodb service at boot
  service: name=mongod state=started enabled=yes


- name: Create the mongodb configuration file with auth
  template: src=mongodb.conf.j2 dest=/etc/mongod.conf owner=mongodb group=mongodb mode=0400
  notify: restart mongodb

- name: Bakcup Mongo Daily 
  template: src=backupDailyMongo.sh dest=/etc/cron.daily/backupDailyMongoDb mode=0755 owner=root group=root
